"use client"

import { useEffect, useState } from "react"

type Exam = { id: string; title: string; description?: string | null; durationMins: number; startTime: string; endTime: string; status: string; subjects: Array<{ id: string; name: string; _count?: { questions: number } }>; _count?: { sessions: number } }
const blank = { title: "", description: "", durationMins: "60", startTime: "", endTime: "", status: "DRAFT", subjects: "" }

export default function AdminExams() {
  const [exams, setExams] = useState<Exam[]>([])
  const [form, setForm] = useState(blank)
  const [editing, setEditing] = useState<string | null>(null)
  const [message, setMessage] = useState("")
  async function load() { const response = await fetch("/api/admin/exams"); const data = await response.json(); if (response.ok) setExams(data.exams); else setMessage(data.error) }
  useEffect(() => { load() }, [])
  function update(field: keyof typeof blank, value: string) { setForm((previous) => ({ ...previous, [field]: value })) }
  function edit(exam: Exam) { setEditing(exam.id); setForm({ title: exam.title, description: exam.description ?? "", durationMins: String(exam.durationMins), startTime: exam.startTime.slice(0, 16), endTime: exam.endTime.slice(0, 16), status: exam.status, subjects: exam.subjects.map((subject) => subject.name).join(", ") }) }
  async function save(event: React.FormEvent) { event.preventDefault(); const payload = { ...form, durationMins: Number(form.durationMins), subjects: form.subjects.split(",").map((name) => ({ name: name.trim() })).filter((subject) => subject.name) }; const response = await fetch(editing ? `/api/admin/exams/${editing}` : "/api/admin/exams", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) setMessage(data.error); else { setMessage(editing ? "Exam updated" : "Exam created"); setEditing(null); setForm(blank); load() } }
  async function remove(id: string) { if (!confirm("Delete this exam and its questions?")) return; await fetch(`/api/admin/exams/${id}`, { method: "DELETE" }); load() }
  return <div><div className="mb-6 flex items-center justify-between"><h1 className="text-2xl font-bold text-gray-800">Exam Management</h1><button onClick={() => { setEditing(null); setForm(blank) }} className="rounded-md bg-blue-600 px-4 py-2 text-sm text-white">New exam</button></div>{message && <p className="mb-4 rounded-md bg-blue-50 p-3 text-sm text-blue-700">{message}</p>}<form onSubmit={save} className="mb-6 grid gap-3 rounded-lg bg-white p-4 shadow md:grid-cols-2"><input required placeholder="Exam title" value={form.title} onChange={(event) => update("title", event.target.value)} className="rounded border p-2 md:col-span-2" /><textarea placeholder="Description" value={form.description} onChange={(event) => update("description", event.target.value)} className="rounded border p-2 md:col-span-2" /><input required type="number" min="1" placeholder="Duration in minutes" value={form.durationMins} onChange={(event) => update("durationMins", event.target.value)} className="rounded border p-2" /><select value={form.status} onChange={(event) => update("status", event.target.value)} className="rounded border p-2"><option>DRAFT</option><option>SCHEDULED</option><option>ACTIVE</option><option>COMPLETED</option></select><label className="text-sm">Starts<input required type="datetime-local" value={form.startTime} onChange={(event) => update("startTime", event.target.value)} className="mt-1 block w-full rounded border p-2" /></label><label className="text-sm">Ends<input required type="datetime-local" value={form.endTime} onChange={(event) => update("endTime", event.target.value)} className="mt-1 block w-full rounded border p-2" /></label><input placeholder="Subjects, separated by commas" value={form.subjects} onChange={(event) => update("subjects", event.target.value)} className="rounded border p-2 md:col-span-2" /><button className="rounded bg-green-600 px-4 py-2 text-white md:col-span-2">{editing ? "Update exam" : "Create exam"}</button></form><div className="grid gap-4 md:grid-cols-2">{exams.map((exam) => <article key={exam.id} className="rounded-lg bg-white p-5 shadow"><div className="flex items-start justify-between"><h2 className="text-lg font-semibold">{exam.title}</h2><span className="rounded bg-blue-100 px-2 py-1 text-xs">{exam.status}</span></div><p className="mt-2 text-sm text-gray-500">{exam.description}</p><p className="mt-3 text-sm">{new Date(exam.startTime).toLocaleString()} · {exam.durationMins} minutes</p><p className="text-sm text-gray-500">Subjects: {exam.subjects.map((subject) => `${subject.name} (${subject._count?.questions ?? 0})`).join(", ") || "None"}</p><div className="mt-4 flex gap-3"><button onClick={() => edit(exam)} className="text-blue-600">Edit</button><button onClick={() => remove(exam.id)} className="text-red-600">Delete</button></div></article>)}</div></div>
}