"use client"

import { useEffect, useRef, useState } from "react"
import Papa from "papaparse"

type Question = { id: string; text: string; subjectId: string; correctOption: string; options: Array<{ id: string; text: string }>; marks: number; negativeMarks: number; difficulty: number; subject?: { name: string; exam?: { title: string } } }
const blank = { subjectId: "", text: "", options: "Option A|Option B|Option C|Option D", correctOption: "A", marks: "1", negativeMarks: "0", difficulty: "1" }

export default function AdminQuestions() {
  const [questions, setQuestions] = useState<Question[]>([])
  const [form, setForm] = useState(blank)
  const [editing, setEditing] = useState<string | null>(null)
  const [message, setMessage] = useState("")
  const fileInput = useRef<HTMLInputElement>(null)
  async function load() { const response = await fetch("/api/admin/questions"); const data = await response.json(); if (response.ok) setQuestions(data.questions); else setMessage(data.error) }
  useEffect(() => { load() }, [])
  function update(field: keyof typeof blank, value: string) { setForm((previous) => ({ ...previous, [field]: value })) }
  async function save(event: React.FormEvent) { event.preventDefault(); const payload = { ...form, options: form.options.split("|").map((text, index) => ({ id: String.fromCharCode(65 + index), text: text.trim() })), marks: Number(form.marks), negativeMarks: Number(form.negativeMarks), difficulty: Number(form.difficulty) }; const response = await fetch(editing ? `/api/admin/questions/${editing}` : "/api/admin/questions", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) setMessage(data.error); else { setMessage(editing ? "Question updated" : "Question created"); setForm(blank); setEditing(null); load() } }
  async function remove(id: string) { if (!confirm("Delete this question?")) return; await fetch(`/api/admin/questions/${id}`, { method: "DELETE" }); load() }
  function edit(question: Question) { setEditing(question.id); setForm({ subjectId: question.subjectId, text: question.text, options: question.options.map((option) => option.text).join("|"), correctOption: question.correctOption, marks: String(question.marks), negativeMarks: String(question.negativeMarks), difficulty: String(question.difficulty) }) }
  function importCsv(file: File) { Papa.parse<Record<string, string>>(file, { header: true, skipEmptyLines: true, complete: async (result) => { const response = await fetch("/api/admin/questions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ questions: result.data.map((row) => ({ ...row, options: row.options?.split("|").map((text, index) => ({ id: String.fromCharCode(65 + index), text: text.trim() })) })) }) }); const data = await response.json(); setMessage(response.ok ? `${data.questions.length} questions imported` : data.error); load() } }) }
  return <div><div className="mb-6 flex items-center justify-between"><h1 className="text-2xl font-bold text-gray-800">Question Bank</h1><div className="flex gap-2"><button onClick={() => fileInput.current?.click()} className="rounded-md border bg-white px-4 py-2 text-sm">Import CSV</button><input ref={fileInput} hidden type="file" accept=".csv" onChange={(event) => event.target.files?.[0] && importCsv(event.target.files[0])} /><button onClick={() => { setEditing(null); setForm(blank) }} className="rounded-md bg-blue-600 px-4 py-2 text-sm text-white">New question</button></div></div>{message && <p className="mb-4 rounded-md bg-blue-50 p-3 text-sm text-blue-700">{message}</p>}<form onSubmit={save} className="mb-6 grid gap-3 rounded-lg bg-white p-4 shadow md:grid-cols-2"><input required placeholder="Subject ID" value={form.subjectId} onChange={(event) => update("subjectId", event.target.value)} className="rounded border p-2" /><input required placeholder="Question text" value={form.text} onChange={(event) => update("text", event.target.value)} className="rounded border p-2 md:col-span-2" /><input required placeholder="Options separated by |" value={form.options} onChange={(event) => update("options", event.target.value)} className="rounded border p-2 md:col-span-2" /><input placeholder="Correct option (A)" value={form.correctOption} onChange={(event) => update("correctOption", event.target.value)} className="rounded border p-2" /><input type="number" min="1" placeholder="Marks" value={form.marks} onChange={(event) => update("marks", event.target.value)} className="rounded border p-2" /><input type="number" min="0" placeholder="Negative marks" value={form.negativeMarks} onChange={(event) => update("negativeMarks", event.target.value)} className="rounded border p-2" /><input type="number" min="1" placeholder="Difficulty" value={form.difficulty} onChange={(event) => update("difficulty", event.target.value)} className="rounded border p-2" /><button className="rounded bg-green-600 px-4 py-2 text-white md:col-span-2">{editing ? "Update question" : "Create question"}</button></form><div className="overflow-x-auto rounded-lg bg-white shadow"><table className="min-w-full divide-y"><thead><tr className="bg-gray-50 text-left text-xs uppercase text-gray-500"><th className="p-3">Question</th><th className="p-3">Subject</th><th className="p-3">Answer</th><th className="p-3">Actions</th></tr></thead><tbody className="divide-y">{questions.map((question) => <tr key={question.id}><td className="max-w-xl p-3">{question.text}</td><td className="p-3">{question.subject?.name ?? question.subjectId}</td><td className="p-3">{question.correctOption}</td><td className="p-3"><button onClick={() => edit(question)} className="mr-3 text-blue-600">Edit</button><button onClick={() => remove(question.id)} className="text-red-600">Delete</button></td></tr>)}</tbody></table></div></div>
}